apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode1-deployment
  labels:
    app: episode4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode4
  template:
    metadata:
      labels:
        app: episode4
    spec:
      containers:
      - name: frontend
        image: khadijahmehmood/frontendep4:latest
        ports:
        - containerPort: 5003
      - name: backend
        image: khadijahmehmood/backendep4:latest
        ports:
        - containerPort: 3003